### ISSUE TITLE
Incremental/no-change builds super slow

### ISSUE THREAD

**Issue by catskul** [ignitionrobotics/ign-cmake#92]
`ign-cmake` is always the long pole in the tent when building. 

"package_source step" and  "Generating API documentation with Doxygen" anecdotally appear to be partially to blame and seem to run when nothing else has changed.

Not doing anything special. Have seen it when compiling ign-cmake manually (`mkdir build; cd build; cmake ../; make; make;` ...) and also using `colcon build`

**Comment by mjcarroll** [comment]
@catskul A substantial amount of the `ign-cmake` build time can typically be attributed to the multiple sub-packages that it builds, which each require an additional `cmake` invocation.

If you want to accelerate it, you can disable these tests by setting a corresponding command line flag for cmake `-DBUILD_TESTING=0`

```
cmake ..  0.94s user 0.27s system 100% cpu 1.212 total
make  82.20s user 24.29s system 99% cpu 1:46.62 total
make  34.90s user 7.56s system 99% cpu 42.625 total
```

```
cmake .. -DBUILD_TESTING=0  0.59s user 0.20s system 99% cpu 0.788 total
make  0.02s user 0.01s system 99% cpu 0.024 total
make  0.02s user 0.01s system 99% cpu 0.024 total
```

Additionally, when building with `colcon`, you can add a `colcon.pkg` file to specifically disable building tests for ignition-cmake

```
{
  "cmake-args": [
    "-DBUILD_TESTING=0",
  ]
}
```

```
$ colcon build --packages-select ignition-cmake2
Starting >>> ignition-cmake2
Finished <<< ignition-cmake2 [0.19s]   
```

**Comment by mjcarroll** [comment]
I believe this should address your issue, feel free to reopen if it does not.

**Comment by mxgrey** [comment]
I wonder if perhaps `BUILD_TESTING` should be off by default, since it really only matters for the build farm, and it's easy enough for us to explicitly enable it for the build farm.

**Comment by chapulina** [comment]
I believe we've been following CTest's convention, on by default: https://cmake.org/cmake/help/v3.7/module/CTest.html . This also matches what `ament_cmake` does, for example.

**Comment by mxgrey** [comment]
Sure, but I think the convention is causing more harm than good here. The convention expects C/C++ compiled targets that can be built once and then that's it. The `ignition-cmake` tests on the other hand are testing the build system, and it seems they're not smart enough to know when it actually matters for them to be rebuilt.

I don't see a point in following a convention that didn't have our use case in mind and which is creating a needlessly sub-optimal experience for our users.

**Comment by chapulina** [comment]
Ok, I understand that `ign-cmake`'s tests are different in nature. But they're not the only tests that take a long time to compile :wink: Even though other long tests do know that they don't need to be rebuilt.

Are you suggesting we default `BUILD_TESTING` to off only for this library or for all of Ignition?

As a reference, a while back we made the move to default to not compile tests on [Gazebo-classic](https://osrf-migration.github.io/gazebo-gh-pages/#!/osrf/gazebo/pull-requests/2499/page/1).

IMO, we need very strong reasons to go against convention - because that in itself can be confusing for newcomers.

**Comment by mjcarroll** [comment]
`BUILD_TESTING=ON` normally makes a lot of sense.  In this case, we're essentially forking out a whole bunch of `cmake` invocations, and they are unavoidable because they break cmake's change detection.  It adds (on a relatively fast system) a minute or so of additional churn with no real value (as nothing has changed).

I think this is actually slightly against CTest convention, because we are executing the tests during the `make` call and not just building them.

I would propose:

a) disabling BUILD_TESTING by default on only this repo
b) Hiding these tests behind another build flag (BUILD_BUILDSYSTEM_TESTING), and turn this flag on by default in CI.
c) Put these tests in a separate package that can be skipped by most builds.
d) Find a way to put these in a place that will run with `make test` like it's supposed to

B seems like the easiest middle ground with D probably being the "most correct" but most work.

**Comment by chapulina** [comment]
B sounds like a good compromise to me :+1:

**Comment by mxgrey** [comment]
I like every single one of @mjcarroll 's suggestions. I think any one of them would be a great solution to this problem.
